// Code generated by coz. DO NOT EDIT.
/**
 * Password util for the-framework
 * @module the-password
 */
'use strict'

const _d = (m) => (m && 'default' in m) ? m.default : m

const ThePassword_ = require('./ThePassword')
const create_ = require('./create')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.ThePassword = _d(ThePassword_)
exports.create = _d(create_)

module.exports = _d(default__)
